FROM alpine:3.16

RUN apk add --no-cache git ca-certificates \
    && rm -rf /var/cache/apk/* && \
    update-ca-certificates
WORKDIR /usr/bin/
COPY cloudsql-exporter .
ENTRYPOINT ["/usr/bin/cloudsql-exporter"]
